name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022, ubuntu-20.04, ubuntu-22.04, macos-11, macos-12 ]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Build with Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect
          conan export raknet --version 4.081
          conan create . --build=missing -c tools.cmake.cmaketoolchain:generator=Ninja
