name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheel (${{ matrix.python }}-${{ matrix.machine.platform }})
    runs-on: ${{ matrix.machine.os }}
    strategy:
      fail-fast: false
      matrix:
        machine:
          - { os: 'windows-latest', platform: 'win_amd64' }
          - { os: 'ubuntu-latest', platform: 'manylinux_x86_64' }
          - { os: 'macos-latest', platform: 'macosx_x86_64' }
        python: [ "cp39", "cp310", "cp311", "cp312", "pp39", "pp310" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.machine.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python }}-${{ matrix.machine.platform }}
          path: ./wheelhouse/*.whl