name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-11 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  release:
    name: Release
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build_wheels, make_sdist ]
    environment: pypi
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1